version: '3'

services:
  mordhau:
    restart: always
    container_name: mordhau
    image: cm2network/mordhau
    volumes:
      - ./mordhau-data:/home/steam/mordhau-dedicated/
      - ./Engine.ini:/home/steam/mordhau-dedicated/cfg/Engine.ini
      - ./Game.ini:/home/steam/mordhau-dedicated/cfg/Game.ini
    environment:
      - SERVER_ADMINPW="veli123"
      - SERVER_PW="veliveli"
      - SERVER_NAME="Youls Swords"
      - SERVER_MAXPLAYERS=6
      - SERVER_PORT=7777
      - SERVER_QUERYPORT=27015
      - SERVER_BEACONPORT=15000
    ports:
      # Game client port:
      - "7777:7777/udp"
      # Peer port:
      - "7778:7778/udp"
      # Beacon port:
      - "15000:15000/udp"
      # Steam server-list port:
      - "27015:27015/udp"
    networks:
        - default